[target.xtensa-esp32-espidf]
runner = "espflash flash --monitor --chip esp32"
linker = "ldproxy"         # <- wieder aktivieren

[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]


[env]
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }
# für ältere Bindgen-Signedness-Themen (unschädlich):
BINDGEN_EXTRA_CLANG_ARGS = { value = "-fsigned-char" }
BINDGEN_EXTRA_CLANG_ARGS_xtensa_esp32_espidf = { value = "-fsigned-char" }
